### PR TITLE
Add light1 and light2 textures

### PR DESCRIPTION
**Pull request by acerspyro**
I made some knock-offs of trak's lights from trak4.
Please tell me what has to be done in order to credit him (derived work), our licenses are compatible.

### CODE REVIEW

**Comment by TheAssassin** [comment]
@acerspyro noone will give you legal advice, because they could be held liable. If you tell me what licenses both of you use, I can make a suggestion though.

**Comment by acerspyro** [comment]
@TheAssassin We're both using CC-BY-SA, in theory all I need to do is credit him, I just don't know where and if it's necessary as he's already credited somewhere else in the game.

**Comment by TheAssassin** [comment]
You can write something like

```
Copyright 2017 <your name>
Copyright <year>-201x <other name>

Licensed under the conditions of CC-By-SA v<version>. You can find a copy of the license <here>.
```

I think that should suffice the crediting aspect.

By the way, it's "By".

**Comment by acerspyro** [comment]
To be honest, I think my texture is different enough from his, as they don't really look that much alike.

**Comment by TheAssassin** [comment]
Is it a derived work? Like, did you take his, put it in e.g. GIMP, changed colors and published the result? Only in this case it's considered derived, and only in this case the license would be effective and you had to credit him.

If you just think you have to credit someone for having the idea or for creating a specific design, it's not a violation of the license I guess. If I paint my bike red, and you paint your bike in the exact same color, it's not derived from the original work.

What you were thinking of is a trademark thing, like you can't redraw GitHub's logo, and then use it for your own company. Back to the bikes: If I had a trademark on red bikes, and you would paint yours red, I could sue you for violating my trademark. But that doesn't have anything to do with the license.

On the other hand, I think it's always a good idea to credit people for their ideas. It shows that you're a fair player, and the other parties might get notified and see that their ideas are good. That view comes from my scientific work, where you are even required to credit people properly for their work, even if you don't cite them directly.

As usual, the above is no legal advice, just my current opinion on the situation.

**Comment by acerspyro** [comment]
Alright, it does not need crediting then. It is ready to merge.

**Review by TheAssassin — APPROVED** [review]

**Comment by TheAssassin** [comment]
Looks good to me. I'll leave merging to someone who knows more about textures than me though.

**Pull request merged**
